name: mrf_gfs_high_water_probability_para
dataset:
    uris:
        - https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para/nwm.{{datetime:%Y%m%d}}/medium_range_mem1/nwm.t{{datetime:%H}}z.medium_range.channel_rt_1.f{{range:3,121,3,%03d}}.conus.nc
        - https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para/nwm.{{datetime:%Y%m%d}}/medium_range_mem2/nwm.t{{datetime:%H}}z.medium_range.channel_rt_2.f{{range:3,121,3,%03d}}.conus.nc
        - https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para/nwm.{{datetime:%Y%m%d}}/medium_range_mem3/nwm.t{{datetime:%H}}z.medium_range.channel_rt_3.f{{range:3,121,3,%03d}}.conus.nc
        - https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para/nwm.{{datetime:%Y%m%d}}/medium_range_mem4/nwm.t{{datetime:%H}}z.medium_range.channel_rt_4.f{{range:3,121,3,%03d}}.conus.nc
        - https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para/nwm.{{datetime:%Y%m%d}}/medium_range_mem5/nwm.t{{datetime:%H}}z.medium_range.channel_rt_5.f{{range:3,121,3,%03d}}.conus.nc
        - https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para/nwm.{{datetime:%Y%m%d}}/medium_range_mem6/nwm.t{{datetime:%H}}z.medium_range.channel_rt_6.f{{range:3,121,3,%03d}}.conus.nc
    repeat: PT6H
    repeat_ref_time: 0:00:00
    delay: PT8H
    expect: PT9H
    ping: PT5M
    transfer: all
    clean: True
process:
    script: .\process.py
