FROM postgis/postgis:15-3.3

WORKDIR /app

COPY rnr_schema_dump_20240612.dump /docker-entrypoint-initdb.d/
COPY init_roles.sql /docker-entrypoint-initdb.d/

# These files run sequentially. Making the first letter be z so it runs last
RUN mv /docker-entrypoint-initdb.d/rnr_schema_dump_20240612.dump /docker-entrypoint-initdb.d/z_rnr_schema_dump_20240612.dump

COPY restore_db.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/restore_db.sh