service: viz-raster-processing
provider:
  name: aws
  deploymentBucket: 
    name: ${env:DEPLOYMENT_BUCKET}
    serverSideEncryption: AES256
  region: ${env:AWS_DEFAULT_REGION}
functions:
  lambda:
    name: ${env:LAMBDA_NAME}
    image: ${env:AWS_ACCOUNT_ID}.dkr.ecr.${env:AWS_DEFAULT_REGION}.amazonaws.com/${env:IMAGE_REPO_NAME}:${env:IMAGE_TAG}
    role: ${env:LAMBDA_ROLE_ARN}
    memorySize: 2560
    timeout: 900
    ephemeralStorageSize: 1024
    environment:
      OUTPUT_BUCKET: ${env:OUTPUT_BUCKET}
      OUTPUT_PREFIX: ${env:OUTPUT_PREFIX}

