service: viz-schism-fim-processing
provider:
  name: aws
  deploymentBucket: 
    name: ${env:INPUTS_BUCKET}
    serverSideEncryption: AES256
  region: ${env:AWS_DEFAULT_REGION}
functions:
  lambda:
    name: ${env:LAMBDA_NAME}
    image: ${env:AWS_ACCOUNT_ID}.dkr.ecr.${env:AWS_DEFAULT_REGION}.amazonaws.com/${env:IMAGE_REPO_NAME}:${env:IMAGE_TAG}
    role: ${env:LAMBDA_ROLE_ARN}
    memorySize: 5000
    timeout: 900
    ephemeralStorageSize: 2048
    environment:
      MAX_VALS_BUCKET: ${env:MAX_VALS_BUCKET}
      INPUTS_BUCKET: ${env:INPUTS_BUCKET}
      INPUTS_PREFIX: ${env:INPUTS_PREFIX}
      OUTPUTS_BUCKET: ${env:OUTPUTS_BUCKET}
      OUTPUTS_PREFIX: ${env:OUTPUTS_PREFIX}
      VIZ_DB_DATABASE: ${env:VIZ_DB_DATABASE}
      VIZ_DB_HOST: ${env:VIZ_DB_HOST}
      VIZ_DB_PASSWORD: ${env:VIZ_DB_PASSWORD}
      VIZ_DB_USERNAME: ${env:VIZ_DB_USERNAME}
    vpc:
      securityGroupIds:
        - ${env:SECURITY_GROUP_1}
      subnetIds:
        - ${env:SUBNET_1}
        - ${env:SUBNET_2}
