#!/bin/bash

MQINGESTENDPOINT="${MQINGESTENDPOINT}"
MQUSERNAME="${MQUSERNAME}"
MQPASSWORD="${MQPASSWORD}"
RFC_FCST_USER="${RFC_FCST_USER}"
RFC_FCST_USER_PASSWORD="${RFC_FCST_USER_PASSWORD}"
MQVHOST="${MQVHOST}"

${INITIALIZATION_SCRIPT}