name: ana_anomaly_para
dataset:
    uris:
        - s3-https://$FIM_OUTPUT_BUCKET$.s3.amazonaws.com/common/data/model/com/nwm/para/nwm.{{datetime:%Y%m%d}}/analysis_assim/nwm.t{{datetime:%H}}z.analysis_assim.channel_rt.tm00.conus.nc
    window: P14D
    repeat: PT1H
    repeat_ref_time: 0:00:00
    delay: PT1H55M
    expect: PT2H35M
    transfer: all
    clean: True
    acceptable_uris_missing: 5%
process:
    script: .\process.py
    interval_ref_time: 0:00:00
    interval: PT24H
    timeout: PT2H
