#!/bin/bash

FORECASTDB="${FORECASTDB}"
LOCATIONDB="${LOCATIONDB}"
PGHOST="${PGHOST}"
PGPORT=${PGPORT}
PGUSERNAME="${PGUSERNAME}"
PGPASSWORD="${PGPASSWORD}"
DEPLOYMENT_BUCKET="${DEPLOYMENT_BUCKET}"
RFCDBUSERS="${RFCDBUSERS}"
LOCATIONDBUSERS="${LOCATIONDBUSERS}"

${INITIALIZATION_SCRIPT}

