name: srf_rapid_onset_flooding_probability
dataset:
    uris:
        - https://para.nomads.ncep.noaa.gov/pub/data/nccf/com/nwm/para/nwm.{{datetime:%Y%m%d}}/short_range/nwm.t{{datetime:%H}}z.short_range.channel_rt.f{{range:1,19,1,%03d}}.conus.nc
    window: PT6H
    repeat: PT1H
    repeat_ref_time: 0:00:00
    delay: PT2H47M
    expect: PT3H15M
    ping: PT5M
    transfer: remote
    clean: True
process:
    script: .\process.py
