DROP TABLE IF EXISTS publish.ana_past_14day_max_high_flow_magnitude;

SELECT CHANNELS.FEATURE_ID,
	CHANNELS.FEATURE_ID::TEXT AS FEATURE_ID_STR,
	CHANNELS.STRM_ORDER,
	CHANNELS.NAME,
	CHANNELS.HUC6,
	CHANNELS.NWM_VERS,
	to_char('1900-01-01 00:00:00'::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS reference_time,
	to_char('1900-01-01 00:00:00'::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS valid_time,
	HFM_14DAY.MAX_FLOW_7DAY_CFS AS MAX_FLOW_7DAY_CFS,
	CASE
					WHEN MAX_FLOW_7DAY_CFS >= THRESHOLDS.RF_50_0_17C THEN '2'
					WHEN MAX_FLOW_7DAY_CFS >= THRESHOLDS.RF_25_0_17C THEN '4'
					WHEN MAX_FLOW_7DAY_CFS >= THRESHOLDS.RF_10_0_17C THEN '10'
					WHEN MAX_FLOW_7DAY_CFS >= THRESHOLDS.RF_5_0_17C THEN '20'
					WHEN MAX_FLOW_7DAY_CFS >= THRESHOLDS.RF_2_0_17C THEN '50'
					WHEN MAX_FLOW_7DAY_CFS >= THRESHOLDS.HIGH_WATER_THRESHOLD THEN '>50'
					ELSE NULL
	END AS RECUR_CAT_7DAY,
	HFM_14DAY.MAX_FLOW_14DAY_CFS AS MAX_FLOW_14DAY_CFS,
	CASE
					WHEN MAX_FLOW_14DAY_CFS >= THRESHOLDS.RF_50_0_17C THEN '2'
					WHEN MAX_FLOW_14DAY_CFS >= THRESHOLDS.RF_25_0_17C THEN '4'
					WHEN MAX_FLOW_14DAY_CFS >= THRESHOLDS.RF_10_0_17C THEN '10'
					WHEN MAX_FLOW_14DAY_CFS >= THRESHOLDS.RF_5_0_17C THEN '20'
					WHEN MAX_FLOW_14DAY_CFS >= THRESHOLDS.RF_2_0_17C THEN '50'
					WHEN MAX_FLOW_14DAY_CFS >= THRESHOLDS.HIGH_WATER_THRESHOLD THEN '>50'
					ELSE NULL
	END AS RECUR_CAT_14DAY,
	THRESHOLDS.HIGH_WATER_THRESHOLD AS HIGH_WATER_THRESHOLD,
	THRESHOLDS.RF_2_0_17C AS FLOW_2YR,
	THRESHOLDS.RF_5_0_17C AS FLOW_5YR,
	THRESHOLDS.RF_10_0_17C AS FLOW_10YR,
	THRESHOLDS.RF_25_0_17C AS FLOW_25YR,
	THRESHOLDS.RF_50_0_17C AS FLOW_50YR,
	to_char(now()::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS update_time,
	CHANNELS.GEOM
INTO publish.ana_past_14day_max_high_flow_magnitude
FROM DERIVED.CHANNELS_CONUS CHANNELS
JOIN DERIVED.RECURRENCE_FLOWS_CONUS THRESHOLDS ON (CHANNELS.FEATURE_ID = THRESHOLDS.FEATURE_ID)
JOIN CACHE.MAX_FLOWS_ANA_14DAY HFM_14DAY ON (CHANNELS.FEATURE_ID = HFM_14DAY.FEATURE_ID)
WHERE (THRESHOLDS.HIGH_WATER_THRESHOLD > 0)
				AND HFM_14DAY.MAX_FLOW_14DAY_CFS >= THRESHOLDS.HIGH_WATER_THRESHOLD