DROP TABLE IF EXISTS PUBLISH.ANA_HIGH_FLOW_MAGNITUDE_PRVI;

WITH HIGH_FLOW_MAG AS
	(SELECT MAXFLOWS.FEATURE_ID,
			MAXFLOWS.MAXFLOW_1HOUR_CFS AS MAX_FLOW,
			CASE
							WHEN THRESHOLDS.HIGH_WATER_THRESHOLD = '-9999'::integer::double precision THEN 'Not Available'::text
							WHEN MAXFLOWS.MAXFLOW_1HOUR_CFS >= THRESHOLDS.RF_100_0 THEN '1'::text
							WHEN MAXFLOWS.MAXFLOW_1HOUR_CFS >= THRESHOLDS.RF_50_0 THEN '2'::text
							WHEN MAXFLOWS.MAXFLOW_1HOUR_CFS >= THRESHOLDS.RF_25_0 THEN '4'::text
							WHEN MAXFLOWS.MAXFLOW_1HOUR_CFS >= THRESHOLDS.RF_10_0 THEN '10'::text
							WHEN MAXFLOWS.MAXFLOW_1HOUR_CFS >= THRESHOLDS.RF_5_0 THEN '20'::text
							WHEN MAXFLOWS.MAXFLOW_1HOUR_CFS >= THRESHOLDS.HIGH_WATER_THRESHOLD THEN '>20'::text
							ELSE NULL::text
			END AS RECUR_CAT,
			THRESHOLDS.HIGH_WATER_THRESHOLD AS HIGH_WATER_THRESHOLD,
			THRESHOLDS.RF_2_0 AS FLOW_2YR,
			THRESHOLDS.RF_5_0 AS FLOW_5YR,
			THRESHOLDS.RF_10_0 AS FLOW_10YR,
			THRESHOLDS.RF_25_0 AS FLOW_25YR,
			THRESHOLDS.RF_50_0 AS FLOW_50YR,
			THRESHOLDS.RF_100_0 AS FLOW_100YR
		FROM CACHE.MAX_FLOWS_ANA_PRVI MAXFLOWS
		JOIN DERIVED.RECURRENCE_FLOWS_PRVI THRESHOLDS ON MAXFLOWS.FEATURE_ID = THRESHOLDS.FEATURE_ID
		WHERE (THRESHOLDS.HIGH_WATER_THRESHOLD > 0::double precision
									OR THRESHOLDS.HIGH_WATER_THRESHOLD = '-9999'::integer::double precision)
			AND MAXFLOWS.MAXFLOW_1HOUR_CFS >= THRESHOLDS.HIGH_WATER_THRESHOLD )

SELECT CHANNELS.FEATURE_ID,
	CHANNELS.FEATURE_ID::TEXT AS FEATURE_ID_STR,
	CHANNELS.STRM_ORDER,
	NAME,
	HUC6,
	CHANNELS.NWM_VERS,
	to_char('1900-01-01 00:00:00'::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS reference_time,
	to_char('1900-01-01 00:00:00'::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS valid_time,
	HIGH_FLOW_MAG.MAX_FLOW,
	HIGH_FLOW_MAG.RECUR_CAT,
	HIGH_FLOW_MAG.HIGH_WATER_THRESHOLD AS HIGH_WATER_THRESHOLD,
	HIGH_FLOW_MAG.FLOW_2YR,
	HIGH_FLOW_MAG.FLOW_5YR,
	HIGH_FLOW_MAG.FLOW_10YR,
	HIGH_FLOW_MAG.FLOW_25YR,
	HIGH_FLOW_MAG.FLOW_50YR,
	HIGH_FLOW_MAG.FLOW_100YR,
	to_char(now()::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS update_time,
	CHANNELS.GEOM
INTO PUBLISH.ANA_HIGH_FLOW_MAGNITUDE_PRVI
FROM DERIVED.CHANNELS_PRVI CHANNELS
JOIN HIGH_FLOW_MAG ON CHANNELS.FEATURE_ID = HIGH_FLOW_MAG.FEATURE_ID;