DROP TABLE IF EXISTS PUBLISH.SRF_HIGH_WATER_ARRIVAL_TIME_HI;

WITH ARRIVAL_TIME AS
	(SELECT FORECASTS.FEATURE_ID,
			CASE
							WHEN THRESHOLDS.HIGH_WATER_THRESHOLD = '-9999'::double precision  THEN NULL
							ELSE MIN(FORECASTS.FORECAST_HOUR)
			END AS T_HIGH_WATER_THRESHOLD,
			CASE
							WHEN THRESHOLDS.HIGH_WATER_THRESHOLD = '-9999'::integer::double precision THEN 'Insufficient Data'::text
							WHEN MAX(FORECASTS.FORECAST_HOUR) >= 48 THEN '> 48 hours'::text
							ELSE (max(forecasts.forecast_hour)+1)::text
			END AS T_NORMAL,
			CASE
							WHEN THRESHOLDS.HIGH_WATER_THRESHOLD = '-9999'::integer::double precision THEN 'Insufficient Data'::text
							WHEN MAX(FORECASTS.FORECAST_HOUR) >= 48 THEN 'Outside SRF Forecast Window'::text
							ELSE ((max(forecasts.forecast_hour)+1) - MIN(FORECASTS.FORECAST_HOUR))::text
			END AS DURATION,
			THRESHOLDS.HIGH_WATER_THRESHOLD AS HIGH_WATER_THRESHOLD,
			ROUND((MAX(FORECASTS.STREAMFLOW) * 35.315::double precision)::numeric,
				2) AS MAX_FLOW
		FROM INGEST.NWM_CHANNEL_RT_SRF_HI FORECASTS
		JOIN DERIVED.RECURRENCE_FLOWS_HI THRESHOLDS ON FORECASTS.FEATURE_ID = THRESHOLDS.FEATURE_ID
		JOIN DERIVED.CHANNELS_HI GEO ON FORECASTS.FEATURE_ID = GEO.FEATURE_ID
		WHERE (THRESHOLDS.HIGH_WATER_THRESHOLD > 0::double precision
									OR THRESHOLDS.HIGH_WATER_THRESHOLD = '-9999'::integer::double precision)
			AND (FORECASTS.STREAMFLOW * 35.315::double precision) >= THRESHOLDS.HIGH_WATER_THRESHOLD
		GROUP BY FORECASTS.FEATURE_ID,
			THRESHOLDS.HIGH_WATER_THRESHOLD)

SELECT CHANNELS.FEATURE_ID,
	CHANNELS.FEATURE_ID::TEXT AS FEATURE_ID_STR,
	CHANNELS.NAME,
	CHANNELS.STRM_ORDER,
	CHANNELS.HUC6,
	CHANNELS.NWM_VERS,
	to_char('1900-01-01 00:00:00'::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS reference_time,
	ARRIVAL_TIME.T_HIGH_WATER_THRESHOLD,
	ARRIVAL_TIME.T_NORMAL,
	ARRIVAL_TIME.DURATION,
	ARRIVAL_TIME.HIGH_WATER_THRESHOLD,
	ARRIVAL_TIME.MAX_FLOW,
	to_char(now()::timestamp without time zone, 'YYYY-MM-DD HH24:MI:SS UTC') AS update_time,
	CHANNELS.GEOM
INTO PUBLISH.SRF_HIGH_WATER_ARRIVAL_TIME_HI
FROM DERIVED.CHANNELS_HI CHANNELS
JOIN ARRIVAL_TIME ON CHANNELS.FEATURE_ID = ARRIVAL_TIME.FEATURE_ID;