DROP TABLE IF EXISTS CACHE.MAX_FLOWS_ANA_14DAY;

SELECT MAX_7DAY_FORECAST.FEATURE_ID,
	'1900-01-01 00:00:00'::timestamp without time zone AS reference_time,
	ROUND(MAX_7DAY_FORECAST.STREAMFLOW::numeric, 2)  AS MAX_FLOW_7DAY_cms,
	ROUND(MAX_14DAY_FORECAST.STREAMFLOW::numeric, 2) AS MAX_FLOW_14DAY_cms,
	ROUND((MAX_7DAY_FORECAST.STREAMFLOW * 35.315)::numeric, 2)  AS MAX_FLOW_7DAY_cfs,
	ROUND((MAX_14DAY_FORECAST.STREAMFLOW * 35.315)::numeric, 2) AS MAX_FLOW_14DAY_cfs
INTO CACHE.MAX_FLOWS_ANA_14DAY
FROM INGEST.NWM_CHANNEL_RT_ANA_7DAY_MAX AS MAX_7DAY_FORECAST
JOIN INGEST.NWM_CHANNEL_RT_ANA_14DAY_MAX AS MAX_14DAY_FORECAST ON (MAX_7DAY_FORECAST.FEATURE_ID = MAX_14DAY_FORECAST.FEATURE_ID);