DROP TABLE IF EXISTS CACHE.MAX_FLOWS_SRF_PRVI;

SELECT FORECASTS.FEATURE_ID,
	'1900-01-01 00:00:00'::timestamp without time zone AS reference_time,
	ROUND(MAX(FORECASTS.STREAMFLOW)::numeric, 2) AS MAXFLOW_48HOUR_cms,
	ROUND((MAX(FORECASTS.STREAMFLOW) * 35.315)::numeric, 2) AS MAXFLOW_48HOUR_cfs
INTO CACHE.MAX_FLOWS_SRF_PRVI
FROM INGEST.NWM_CHANNEL_RT_SRF_PRVI FORECASTS
GROUP BY FORECASTS.FEATURE_ID;