DROP TABLE IF EXISTS CACHE.MAX_FLOWS_SRF;

SELECT FORECASTS.FEATURE_ID,
    '1900-01-01 00:00:00'::timestamp without time zone AS reference_time,
    ROUND(MAX(FORECASTS.STREAMFLOW)::numeric, 2) AS MAXFLOW_18HOUR_cms,
	ROUND((MAX(FORECASTS.STREAMFLOW) * 35.315)::numeric, 2) AS MAXFLOW_18HOUR_cfs
INTO CACHE.MAX_FLOWS_SRF
FROM INGEST.NWM_CHANNEL_RT_SRF FORECASTS
GROUP BY FORECASTS.FEATURE_ID;