name: PyTest Suite

on: [pull_request]

jobs:
  # lint_and_format:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-python@v5
  #     with:
  #       python-version: "3.11"

  #   - name: Install pre-commit
  #     run: |
  #         python -m pip install pre-commit

  #   - name: Run pre-commit hooks on all files
  #     run: |
  #         pre-commit run --all-files

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set UV_HTTP_TIMEOUT
      run: echo "UV_HTTP_TIMEOUT=600" >> $GITHUB_ENV

    - name: Install python dependencies and packages
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install -r Source/RnR/requirements.txt

    - name: Echo package versions
      run: |
        source .venv/bin/activate
        uv pip freeze

    - name: Run unit tests
      run: |
        source .venv/bin/activate
        cd Source/RnR
        pytest -s